graphical:
  enabled: false
console:
  enabled: true
  post_analysis_on: true
  out_dir_path: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  characters:
    ground: " "
    obstacle: "#"
    agent: "A"
    flower: "F"
